### ISSUE TITLE
Add button stretched a bit

### ISSUE THREAD

**Issue by bjarnef** [bomortensen/Our.Umbraco.OpeningHours#12]
It seems the add button is stretched a bit, but not in the grid (Umbraco 7.4+), where its parent use `umb-grid` class ... the `usky-grid` class is probably the original and old stuff.. and it seems Umbraco forms overwrite it..

![image](https://cloud.githubusercontent.com/assets/2919859/17457536/259a57fe-5bfb-11e6-8447-5342aa8a4f1c.png)

![image](https://cloud.githubusercontent.com/assets/2919859/17457538/2bd20068-5bfb-11e6-806f-d72a9b779bb1.png)

Does it affect OpeningHours to use `umb-grid` class instead or does it mess up stuff in < 7.4. versions?

**Comment by bjarnef** [comment]
I have submitted an issue here, since it should be fixed in Umbraco Forms: http://issues.umbraco.org/issue/CON-1141

**Comment by abjerner** [comment]
Testing with default Umbraco 7.5.3 and whatever Umbraco Forms it ships with, the add button is now correctly 30x30 :D
