### ISSUE TITLE
OpeningHoursDay contains two properties for weekday

### ISSUE THREAD

**Issue by bjarnef** [bomortensen/Our.Umbraco.OpeningHours#14]
It is a bit confusing that OpeningHoursDay model contains both a property `WeekDay` and `Weekday`.

```
@{
    OpeningHoursModel openingHours = Model.Content.GetOpeningHours();

    var upcomingDays = openingHours.GetUpcomingDays(7);

    <h3>Åbningstider</h3>

    foreach (var day in upcomingDays)
    {
        <strong>@day.WeekDayName</strong><br />
        @day.WeekDay<br />
        @day.Weekday<br /><br />
    }
}
```
![image](https://cloud.githubusercontent.com/assets/2919859/20941308/29d1e57a-bbf6-11e6-8cd8-b4e9ece0c435.png)

It seems that `WeekDay` return the same as `WeekDayName` - name of the actually weekday name, while `Weekday` returns Our.Umbraco.OpeningHours.Model.Items.OpeningHoursWeekdayItem

![image](https://cloud.githubusercontent.com/assets/2919859/20941286/0a823a12-bbf6-11e6-97ed-1d6756435141.png)

**Comment by abjerner** [comment]
`WeekDay` is actually an enum, but I can see the possible confusion between the two names. I have pushed a commit that changes `WeekDay` to `DayOfWeek` ;)
