### ISSUE TITLE
Add option to hide label

### ISSUE THREAD

**Issue by bjarnef** [bomortensen/Our.Umbraco.OpeningHours#18]
I wouldbe great if you could an a config checkbox to decide whether to hide label (doctype property) or not, so you can use full width.

e.g. like Nested Content does:

![image](https://cloud.githubusercontent.com/assets/2919859/20946019/6ec90434-bc09-11e6-9173-a892a35b48df.png)

**Comment by abjerner** [comment]
Closing this issue as @bjarnef's  pull request  now have been merged.
