### ISSUE TITLE
Add unique CSS class name to property editors

### ISSUE THREAD

**Issue by abjerner** [bomortensen/Our.Umbraco.OpeningHours#7]
As pointed out by @bjarnef in #3, the property editors should have a unique CSS class name so our CSS styles only target the three property editors, and not everything else.

**Comment by bjarnef** [comment]
@abjerner usually I also add a class at "root" level, so you e.g. can use core styling for elements like buttons, but sometimes you want to tweak it a bit like padding or margin.

**Comment by abjerner** [comment]
@bjarnef Yup, we do the same thing with our editors. For the OpeningHours editors, the class name on the root element is now ... wait for it ... `OpeningHours` :tada:
